# Generated by Django 3.1.6 on 2021-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images_url',
            field=models.ImageField(height_field='350', max_length=250, upload_to=''),
        ),
    ]
