# Generated by Django 3.1.6 on 2021-02-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebnb', '0002_auto_20210202_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images_url',
            field=models.CharField(max_length=250),
        ),
    ]
