# Generated by Django 3.1.6 on 2021-02-02 23:37

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('sharebnb', '0004_auto_20210202_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
