# Generated by Django 3.1.6 on 2021-02-03 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebnb', '0007_remove_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
