# Generated by Django 3.1.6 on 2021-02-04 00:26

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebnb', '0008_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
        ),
    ]
